version: "3.8"

services:
  bocchi:
    image: yaroslavgrud/bocchi-downloader-server-edition:latest
    container_name: bocchi-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_MODE=${BOT_MODE:-stable}

    volumes:
      - bocchi_data:/app/data
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/tmp

    read_only: true
    security_opt:
      - no-new-privileges:true

volumes:
  bocchi_data:
    driver: local
