services:
  bocchi:
    image: yaroslavgrud/bocchi-downloader-server-edition:latest
    container_name: bocchi-bot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      - BOT_MODE=${BOT_MODE:-beta}      # теперь по умолчанию beta
    volumes:
      - ./data:/app/data
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/tmp
    security_opt:
      - no-new-privileges:true
    # read_only: true   # Убрано — теперь бот может писать в /app
    
