name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:   # позволяет запускать вручную

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          push: true
          tags: yaroslavgrud/bocchi-downloader-server-edition:latest

      - name: Docker Scout security scan
        uses: docker/scout-action@cd72f264beff1cd72735de31148b9d3244a0234a
        with:
          command: cves
          image: yaroslavgrud/bocchi-downloader-server-edition:latest
          exit-code: false