name: "Удалить лишние пустые строки в workflow"

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fix-empty-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Убрать лишние пустые строки в конце файла
        run: |
          for f in .github/workflows/*.yml; do
            sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' "$f"
          done

      - name: Создать Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          commit-message: "🚿 Удалить лишние пустые строки в workflow"
          title: "🚿 Удаление empty-lines (yamllint)"
          body: |
            Автоматическое удаление лишних пустых строк в конце файлов YAML.
            Это исправляет ошибки yamllint о `empty-lines`.
          branch: fix/empty-lines
          delete-branch: true
          token: ${{ secrets.PAT_TOKEN }}